/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import civitas.CivitasJuego;
import civitas.Diario;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class CivitasView extends javax.swing.JFrame implements Vista {
    
    private CivitasJuego juego;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    
    public void setCivitasJuego(CivitasJuego juego)
    {
        this.juego=juego;
        Tablero.setTablero(juego.casillasTablero());
        setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testP51 = new GUI.TestP5();
        Titulo = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        CuadroOperacion = new javax.swing.JTextField();
        LabelRanking = new javax.swing.JLabel();
        PanelRanking = new javax.swing.JScrollPane();
        CuadroRanking = new javax.swing.JTextArea();
        Tablero = new GUI.Tablero();
        CuadroJugador = new GUI.JugadorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Civitas, El Juego");

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Operacion Juego ");

        CuadroOperacion.setEditable(false);

        LabelRanking.setText("Ranking");

        CuadroRanking.setColumns(20);
        CuadroRanking.setRows(5);
        PanelRanking.setViewportView(CuadroRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CuadroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CuadroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelRanking)
                            .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CuadroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CuadroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelRanking)
                        .addGap(18, 18, 18)
                        .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(678, 678, 678))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   
    
    @Override
    public void actualiza() {
        
        LabelRanking.setVisible(false);
        CuadroRanking.setVisible(false);
        PanelRanking.setVisible(false);
      
        //montarTablero();
        CuadroJugador.setJugador(juego.getJugadorActual());
        Tablero.setCasilla(juego.casillasTablero().get(juego.getJugadorActual().getCasillaActual()));
        
        
        if(juego.finDelJuego())
        {
            LabelRanking.setVisible(true);
            CuadroRanking.setText(juego.ranking_string());
            CuadroRanking.setVisible(true);
            PanelRanking.setVisible(true);
        }
        
        
    }
   

    @Override
    public void pausa() {
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
                         "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
    }

    @Override
    public Respuesta comprar() {
       Respuesta aux=Respuesta.NO;
       int opcion= 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
       
       switch(opcion)
       {
           case 0:
               aux=Respuesta.NO;
               break;
               
           case 1:
               aux=Respuesta.SI;
               break;
       }
       
       return aux;
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog aux=new GestionarDialog(this,true);
        
        OperacionInmobiliaria operacion=OperacionInmobiliaria.TERMINAR;
        
        switch(aux.getGestion())
        {
            case 0:
              operacion=OperacionInmobiliaria.CONSTRUIR_CASA;
              break;
            case 1:
              operacion=OperacionInmobiliaria.CONSTRUIR_HOTEL;
              break;
            case 2:
              operacion=OperacionInmobiliaria.TERMINAR;
              break;  
        }
        System.out.println(aux);
        return operacion;
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog aux=new PropiedadDialog(this,true,juego.getJugadorActual());
        //System.out.println(aux.getPropiedad());
        int e=aux.getPropiedad();
        System.out.println(e);
       
        return e;
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operación) {
      
        CuadroOperacion.setText(operación.name());
        if(operación==OperacionJuego.AVANZAR)
            Dado.createInstance(this);
        
        repaint();
    }

    @Override
    public void mostrarEventos() {
        if(!Diario.getInstance().getEventos().isEmpty())
        {
            DiarioDialog diarioD= new DiarioDialog(this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.JugadorPanel CuadroJugador;
    private javax.swing.JTextField CuadroOperacion;
    private javax.swing.JTextArea CuadroRanking;
    private javax.swing.JLabel LabelRanking;
    private javax.swing.JScrollPane PanelRanking;
    private GUI.Tablero Tablero;
    private javax.swing.JLabel Titulo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.TestP5 testP51;
    // End of variables declaration//GEN-END:variables
}
