/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import civitas.CivitasJuego;
import civitas.Diario;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class CivitasView extends javax.swing.JFrame implements Vista {
    
    private CivitasJuego juego;
    private boolean principio=true;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    
    public void setCivitasJuego(CivitasJuego juego)
    {
        this.juego=juego;
        Tablero.setTablero(juego.casillasTablero());
        setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testP51 = new GUI.TestP5();
        OperacionJuegoLabel = new javax.swing.JLabel();
        CuadroOperacion = new javax.swing.JTextField();
        LabelRanking = new javax.swing.JLabel();
        PanelRanking = new javax.swing.JScrollPane();
        CuadroRanking = new javax.swing.JTextArea();
        CuadroJugador = new GUI.JugadorPanel();
        jPanel1 = new javax.swing.JPanel();
        CivitasLabel = new javax.swing.JLabel();
        Tablero = new GUI.Tablero();
        casillasPropietarios1 = new GUI.CasillasPropietarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        OperacionJuegoLabel.setText("Operacion Juego ");

        LabelRanking.setText("Ranking");

        CuadroRanking.setColumns(20);
        CuadroRanking.setRows(5);
        PanelRanking.setViewportView(CuadroRanking);

        CuadroJugador.setBackground(new java.awt.Color(255, 102, 102));
        CuadroJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        CivitasLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        CivitasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CivitasLabel.setText("Civitas, El Juego");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CivitasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(496, 496, 496))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CivitasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CuadroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casillasPropietarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelRanking)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(OperacionJuegoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CuadroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CuadroJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OperacionJuegoLabel)
                            .addComponent(CuadroOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LabelRanking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(casillasPropietarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


   
    
    @Override
    public void actualiza() {     
        
        LabelRanking.setVisible(false);
        CuadroRanking.setVisible(false);
        PanelRanking.setVisible(false);
        
        actualizaFichas();
        Tablero.encenderLuz(juego.getJugadorActual().getCasillaActual());
        Tablero.setCasilla(juego.casillasTablero().get(juego.getJugadorActual().getCasillaActual()));
        CuadroJugador.setJugador(juego.getJugadorActual());
        mostrarPropiedades();
        
        if(juego.finDelJuego())
        {
            LabelRanking.setVisible(true);
            CuadroRanking.setText(juego.ranking_string());
            CuadroRanking.setVisible(true);
            PanelRanking.setVisible(true);
        }
        
        
    }
   

    @Override
    public void pausa() {
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
                         "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
    }

    @Override
    public Respuesta comprar() {
       Respuesta aux=Respuesta.NO;
       int opcion= 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
       
       switch(opcion)
       {
           case 0:
               aux=Respuesta.NO;
               break;
               
           case 1:
               aux=Respuesta.SI;
               break;
       }
       
       return aux;
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog aux=new GestionarDialog(this,true);
        
        OperacionInmobiliaria operacion=OperacionInmobiliaria.TERMINAR;
        
        switch(aux.getGestion())
        {
            case 0:
              operacion=OperacionInmobiliaria.CONSTRUIR_CASA;
              break;
            case 1:
              operacion=OperacionInmobiliaria.CONSTRUIR_HOTEL;
              break;
            case 2:
              operacion=OperacionInmobiliaria.TERMINAR;
              break;  
        }
        return operacion;
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog aux=new PropiedadDialog(this,true,juego.getJugadorActual());
        //System.out.println(aux.getPropiedad());
        int e=aux.getPropiedad();
       
        return e;
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operación) {
      
        CuadroOperacion.setText(operación.name());
        if(operación==OperacionJuego.AVANZAR)
            Dado.createInstance(this);
        
        repaint();
    }

    @Override
    public void mostrarEventos() {
        if(!Diario.getInstance().getEventos().isEmpty())
        {
            DiarioDialog diarioD= new DiarioDialog(this);
        }
    }
    
    
    public void mostrarPropiedades()
    {    
        casillasPropietarios1.borrarTodo();
        for(Casilla n: juego.getTablero().getCasillasPropietarios())
          casillasPropietarios1.setPropiedades((CasillaCalle)n); 
    }
    
    public void actualizaFichas()
    {
        
        for(CasillaComun n : Tablero.casillas)
        {
            n.quitarFicha(juego.getIndiceJugadorActual());
        }
        
        Tablero.casillas.get(juego.getJugadorActual().getCasillaActual()).ponerFicha(juego.getIndiceJugadorActual());
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CivitasLabel;
    private GUI.JugadorPanel CuadroJugador;
    private javax.swing.JTextField CuadroOperacion;
    private javax.swing.JTextArea CuadroRanking;
    private javax.swing.JLabel LabelRanking;
    private javax.swing.JLabel OperacionJuegoLabel;
    private javax.swing.JScrollPane PanelRanking;
    private GUI.Tablero Tablero;
    private GUI.CasillasPropietarios casillasPropietarios1;
    private javax.swing.JPanel jPanel1;
    private GUI.TestP5 testP51;
    // End of variables declaration//GEN-END:variables
}
