/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author Jose
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private CasillaCalle tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(CasillaCalle otro){
        tituloPropiedad=otro;
        
        CuadroNombreProp.setText(tituloPropiedad.getNombre());
        CuadroCasas.setText(Integer.toString(tituloPropiedad.getNumCasas()));
        CuadroHoteles.setText(Integer.toString(tituloPropiedad.getNumHoteles()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CuadroNombreProp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CuadroCasas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CuadroHoteles = new javax.swing.JTextField();

        jLabel1.setText("Nombre de la Propiedad");
        add(jLabel1);

        CuadroNombreProp.setText("jTextField1");
        add(CuadroNombreProp);

        jLabel2.setText("Nº Casas");
        add(jLabel2);

        CuadroCasas.setText("jTextField2");
        add(CuadroCasas);

        jLabel3.setText("Nº Hoteles");
        add(jLabel3);

        CuadroHoteles.setText("jTextField3");
        add(CuadroHoteles);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CuadroCasas;
    private javax.swing.JTextField CuadroHoteles;
    private javax.swing.JTextField CuadroNombreProp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
