/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author Jose
 */
public class PropiedadNombrePrecio extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadNombrePrecio
     */
    public PropiedadNombrePrecio() {
        initComponents();
        
        Alquiler.setOpaque(false);
        Nombre.setOpaque(false);
        Propietario.setOpaque(false);
    }

    public void setPropietario(CasillaCalle n)
    {
        Alquiler.setText(Float.toString(n.getPrecioAlquilerCompleto()));
        Nombre.setText(n.getNombre());
        Propietario.setText(n.getPropietario().getNombre());
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        Propietario = new javax.swing.JTextField();
        Alquiler = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 204)));

        Nombre.setBackground(new java.awt.Color(255, 153, 0));
        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre.setText("jTextField1");
        Nombre.setBorder(null);

        Propietario.setBackground(new java.awt.Color(255, 153, 0));
        Propietario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Propietario.setForeground(new java.awt.Color(255, 255, 255));
        Propietario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Propietario.setText("jTextField2");
        Propietario.setBorder(null);

        Alquiler.setBackground(new java.awt.Color(255, 153, 0));
        Alquiler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Alquiler.setForeground(new java.awt.Color(255, 255, 255));
        Alquiler.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Alquiler.setText("jTextField3");
        Alquiler.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alquiler;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Propietario;
    // End of variables declaration//GEN-END:variables
}
