/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.Casilla;
import java.util.ArrayList;

/**
 *
 * @author carlo
 */
public class Tablero extends javax.swing.JPanel {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }
        public void setTablero(ArrayList<Casilla> casillas)
    {
         /*  
        casillaComun1.setCasilla(casillas.get(0));
        casillaComun2.setCasilla(casillas.get(1));
        casillaComun3.setCasilla(casillas.get(2));
        casillaComun4.setCasilla(casillas.get(3));
        casillaComun5.setCasilla(casillas.get(4));
        casillaComun6.setCasilla(casillas.get(5));
        casillaComun7.setCasilla(casillas.get(6));
        casillaComun8.setCasilla(casillas.get(7));
        casillaComun9.setCasilla(casillas.get(8));
        casillaComun10.setCasilla(casillas.get(9));
        casillaComun11.setCasilla(casillas.get(10));
        casillaComun12.setCasilla(casillas.get(11));
        casillaComun13.setCasilla(casillas.get(12));
        casillaComun14.setCasilla(casillas.get(13));
        casillaComun15.setCasilla(casillas.get(14));
        casillaComun16.setCasilla(casillas.get(15));
        casillaComun17.setCasilla(casillas.get(16));
        casillaComun18.setCasilla(casillas.get(17));
        casillaComun19.setCasilla(casillas.get(18));
        casillaComun20.setCasilla(casillas.get(19));
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casillaComun1 = new GUI.CasillaComun();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(casillaComun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(casillaComun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaComun casillaComun1;
    // End of variables declaration//GEN-END:variables
}
